import type { Metadata } from "next";
import { Montserrat, Luckiest_Guy } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Google Fonts

const montserrat = Montserrat({
  subsets: ["latin"],
  variable:"--font-montserrat",
});

const luckiestGuy = Luckiest_Guy({ 
  weight: "400",
  subsets: ["latin"],
  variable: "--font-luckiest",
});

// Local Fonts

const sugarBomb = localFont({
  src:"../public/fonts/SugarBomb.ttf",
  variable: "--font-sugar",
});

export const metadata: Metadata = {
  title: "HAU 12-12 Snapshot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${luckiestGuy.variable} ${sugarBomb.variable} antialiased bg-[#2D0A31] text-white`}
      >
        {children}
      </body>
    </html>
  );
}
